#!/usr/bin/env bun
// Generates server/assets.generated.ts, the manifest that lets
// `bun build --compile` embed the whole web app inside the binary.
//
// Bun only embeds files it can see as static imports, so the manifest has to be
// written out rather than discovered at runtime. Filenames are content-hashed
// by Vite and change every build, which is exactly why this is generated.

import { readdir, stat } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dir, '..');
const WEB = path.join(ROOT, 'dist', 'web');
const OUT = path.join(ROOT, 'server', 'assets.generated.ts');

async function* walk(dir: string): AsyncGenerator<string> {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(full);
    else yield full;
  }
}

// A fresh clone has no dist/web yet, but static.ts imports this manifest
// unconditionally — so emit an empty one rather than failing. postinstall runs
// this, which is what lets `bun run dev:server` and `tsc` work before the first
// build. The empty manifest also makes the server read assets off disk, which
// is what you want in development.
const files: string[] = [];
try {
  for await (const file of walk(WEB)) files.push(file);
} catch {
  console.log('vibe-os: no dist/web yet — writing an empty asset manifest');
}
files.sort();

// Embedded files have no usable mtime, so the ETag needs another source of
// change. Hash the manifest (names + sizes) into a per-build id.
const hash = createHash('sha256');
for (const file of files) hash.update(`${file}:${(await stat(file)).size}`);
const buildId = hash.digest('hex').slice(0, 12);

const imports: string[] = [];
const entries: string[] = [];

files.forEach((file, i) => {
  const urlPath = `/${path.relative(WEB, file).split(path.sep).join('/')}`;
  const specifier = `../dist/web${urlPath}`;
  imports.push(`import a${i} from ${JSON.stringify(specifier)} with { type: 'file' };`);
  entries.push(`  ${JSON.stringify(urlPath)}: a${i},`);
});

const source = `// @ts-nocheck — generated; \`with { type: 'file' }\` imports are not modelled by tsc.
// Generated by scripts/gen-assets.ts — do not edit.
//
// Maps URL paths to files embedded in the compiled binary. Under \`bun run\`
// these resolve to real paths on disk, so the same code serves both modes.

${imports.join('\n')}

export const BUILD_ID = ${JSON.stringify(buildId)};

export const EMBEDDED: Record<string, string> = {
${entries.join('\n')}
};
`;

await Bun.write(OUT, source);
console.log(`vibe-os: embedded manifest lists ${files.length} asset(s)`);
